apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml


images:
- name: 235251094325.dkr.ecr.us-east-1.amazonaws.com/guestbook
  newTag: 490ac2e2395755e16779f9015ae9def1917785d8
- name: frontend
  newName: guestbook
  newTag: new
