apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml


images:
- name: 431607183994.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 07b7e3768bf15ac5fb35cac0bc1509254ac60d4e
- name: 431607183994.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 59ff368e71f5129e1ab1072ffb071bcea98ea744
- name: frontend
  newName: guestbook
  newTag: new
