apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml


images:
- name: 431607183994.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 459559bb1380d9f151d2faa14fe4bde6a62bb825
- name: frontend
  newName: guestbook
  newTag: new
