apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml


images:
- name: 457472006214.dkr.ecr.us-east-1.amazonaws.com/guestbook
  newTag: 23d38b9ffa3019fb4e1630af6041364ef52719aa
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1dnew